Pekka 2.0/pekka/urls.py
from django.conf.urls import url
from . import views

app_name = 'pekka'

urlpatterns = [
    # login and register
    url(r'^$', views.login_user, name='login_user'),
    url(r'^login_user/$', views.login_user, name='login_user'),
    url(r'^register/$', views.register, name='register'),
    url(r'^logout_user/$', views.logout_user, name='logout_user'),
    # main views
    url(r'^ask/$', views.ask, name='ask'),
    url(r'^answer/$', views.answer, name='answer'),
    url(r'^about/$', views.about, name='about'),
    # question and voting
    url(r'^(?P<question_id>[0-9]+)/$', views.detail, name='detail'),
    url(r'^(?P<answer_id>[0-9]+)/vote_answer/$', views.vote_answer, name='vote_answer'),
    url(r'^(?P<question_id>[0-9]+)/vote_question/$', views.vote_question, name='vote_question'),
    # courses
    url(r'^TDT4140_answer/$', views.course_answer, {'sub_code': 'TDT4140'}, name='TDT4140_answer'),
    url(r'^TDT4110_answer/$', views.course_answer, {'sub_code': 'TDT4110'}, name='TDT4110_answer'),
    url(r'^TDT4145_answer/$', views.course_answer, {'sub_code': 'TDT4145'}, name='TDT4145_answer'),
    url(r'^TDT4180_answer/$', views.course_answer, {'sub_code': 'TDT4180'}, name='TDT4180_answer'),
    url(r'^TTM4100_answer/$', views.course_answer, {'sub_code': 'TTM4100'}, name='TTM4100_answer'),

    url(r'^TDT4140_question/$', views.course_question, {'sub_code': 'TDT4140'}, name='TDT4140_question'),
    url(r'^TDT4110_question/$', views.course_question, {'sub_code': 'TDT4110'}, name='TDT4110_question'),
    url(r'^TDT4145_question/$', views.course_question, {'sub_code': 'TDT4145'}, name='TDT4145_question'),
    url(r'^TDT4180_question/$', views.course_question, {'sub_code': 'TDT4180'}, name='TDT4180_question'),
    url(r'^TTM4100_question/$', views.course_question, {'sub_code': 'TTM4100'}, name='TTM4100_question'),

    url(r'^TDT4140_similar/$', views.course_similar, {'sub_code': 'TDT4140'}, name='TDT4140_similar'),
    url(r'^TDT4110_similar/$', views.course_similar, {'sub_code': 'TDT4110'}, name='TDT4110_similar'),
    url(r'^TDT4145_similar/$', views.course_similar, {'sub_code': 'TDT4145'}, name='TDT4145_similar'),
    url(r'^TDT4180_similar/$', views.course_similar, {'sub_code': 'TDT4180'}, name='TDT4180_similar'),
    url(r'^TTM4100_similar/$', views.course_similar, {'sub_code': 'TTM4100'}, name='TTM4100_similar')
]

Pekka 2.0/website/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^pekka/', include('pekka.urls')),
    url(r'^', include('pekka.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Pekka 2.0/pekka/forms.py
from django import forms
from .models import *


class QuestionForm(forms.Form):

    question_title = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control'}), help_text="")
    question_content = forms.CharField(widget=forms.Textarea(attrs={'cols': 30,
                                                                    'rows': 10,
                                                                    'class': 'form-control'}), help_text="")

    class Meta:
        model = Question
        fields = ('question_title', 'question_content')


class AnswerForm(forms.Form):

    answer_text = forms.CharField(widget=forms.Textarea(attrs={'cols': 30,
                                                               'rows': 10,
                                                               'class': 'form-control'}), help_text="")

    class Meta:
        model = Answer
        fields = 'answer_text'


class QuestionVotesForm(forms.ModelForm):
    UP = '+1'
    REMOVE = '0'
    DOWN = '-1'
    CHOICES = ((UP, 'Upvote'), (REMOVE, 'Remove vote'), (DOWN, 'Downvote'))
    #    CHOICES = ('+1', '0', '-1')
    val = forms.ChoiceField(label="", choices=CHOICES, widget=forms.RadioSelect(), help_text="Don't forget to submit!")

    class Meta:
        model = QuestionVotes
        exclude = ('question', 'user', 'val')


class AnswerVotesForm(forms.ModelForm):
    CHOICES = (('+1', 'Upvote'), ('0', 'Remove vote'), ('-1', 'Downvote'))
    #    CHOICES = ('+1', '0', '-1')
    val = forms.ChoiceField(label="", choices=CHOICES, widget=forms.RadioSelect(), help_text="Don't forget to submit!")

    class Meta:
        model = AnswerVotes
        exclude = ('ans', 'user', 'val')


class UserForm(forms.ModelForm):

    username = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control'}), help_text="")
    email = forms.CharField(widget=forms.EmailInput(attrs={'class': 'form-control'}), help_text="")
    password = forms.CharField(widget=forms.PasswordInput(attrs={'class': 'form-control'}), help_text="")

    class Meta:
        model = User
        fields = ['username', 'email', 'password']


class SignInForm(forms.ModelForm):

    username = forms.CharField(max_length=30, widget=forms.TextInput(attrs={'class': 'form-control'}), help_text="")
    password = forms.CharField(max_length=30, widget=forms.PasswordInput(attrs={'class': 'form-control'}), help_text="")

    class Meta:
        model = User
        fields = ['username', 'password']

Pekka 2.0/pekka/views.py
from django.contrib.auth import authenticate, login
from django.contrib.auth import logout
from django.http import HttpResponseRedirect,  Http404
from django.shortcuts import render
from . forms import *
from .models import *
import datetime
from difflib import SequenceMatcher
from django.shortcuts import redirect


# Adding a StopWord list to avoid comparing insignificant words
StopWords = ['is', 'when', 'what', 'the', 'and', 'where', '?', ' ',
             'should', 'can', 'I', 'i', 'a', 'an', 'are',
             'why', 'how', 'be', 'but', 'if', 'for', 'in',
             'it', 'of', 'or', 'so', 'to', 'about', 'on', "we", 'us']


# Detail is the detailed view of a single question, with associated answers.
def detail(request, question_id):
    try:
        question = Question.objects.get(pk=question_id)
        answers = question.answer_set.all()
        score = question.get_score()
        form = AnswerForm(request.POST)
        if request.method == 'POST':
            if form.is_valid():
                answer = Answer()
                answer.answer_text = form.data['answer_text']
                answer.author = request.user
                answer.answer_time = datetime.datetime.now()
                answer.question = question
                answer.save()
                form = AnswerForm()
                return render(request, 'html_pages/detail.html', {'score': score,
                                                                  'question_title': question.question_title,
                                                                  'question_content': question.question_content,
                                                                  'sub_code': question.sub_code,
                                                                  'answers': answers,
                                                                  'form': form
                                                                  })
    except Question.DoesNotExist:
        raise Http404("Question does not exist")
    return render(request, 'html_pages/detail.html', {'score': score,
                                                      'question_title': question.question_title,
                                                      'question_content': question.question_content,
                                                      'sub_code': question.sub_code,
                                                      'answers': answers,
                                                      'form': form
                                                      })


def vote_question(request, question_id):
    question = Question.objects.get(pk=question_id)
    form = QuestionVotesForm()
    previous_page = request.META.get('HTTP_REFERER')
    if request.method == 'POST':
        form = QuestionVotesForm(request.POST)
        if form.is_valid():
            qv = QuestionVotes()
            qv.user = request.user
            qv.question = question
            qv.val = form.data['val']
            if not QuestionVotes.objects.filter(question=qv.question, user=qv.user):
                qv.save()
            else:
                existing_votes = QuestionVotes.objects.filter(question=question, user=qv.user)
                for vote in existing_votes:
                    vote.delete()
                qv.save()
            return HttpResponseRedirect('/' + question_id)
    return render(request, template_name='html_pages/vote_question.html', context={
            'question_id': question_id,
            'question_title': question.question_title,
            'question_content': question.question_content,
            'score': question.get_score(),
            'form': form,
            'previous_page': previous_page
            })


def vote_answer(request, answer_id):
    answer = Answer.objects.get(pk=answer_id)
    form = AnswerVotesForm()
    current_score = answer.get_score()
    if request.method == 'POST':
        form = AnswerVotesForm(request.POST)
        if form.is_valid():
            answ = AnswerVotes()
            answ.user = request.user
            answ.ans = answer
            answ.val = form.data['val']
            if not AnswerVotes.objects.filter(ans=answer, user=answ.user):
                answ.save()
            else:
                existing_votes = AnswerVotes.objects.filter(ans=answer, user=answ.user)
                for vote in existing_votes:
                    vote.delete()
                answ.save()
            return HttpResponseRedirect('/' + str(answer.question.id))
    return render(request, template_name='html_pages/vote_answer.html', context={
            'question': answer.question,
            'answer': answer,
            'score': current_score,
            'form': form
            })
# ------------------------------------------------------------------------------------------------------------------


def course_answer(request, sub_code):
    all_questions_with_sub_code = Question.objects.filter(sub_code=sub_code)
    context = {
        'all_questions_with_sub_code': all_questions_with_sub_code,
        'sub_code': sub_code
    }
    return render(request, 'courses/course_answer.html', context=context)


def course_similar(request, sub_code):
    all_questions_with_sub_code = Question.objects.filter(sub_code=sub_code)
    similar_questions = []
    try:
        a = Question.objects.filter(sub_code=sub_code).latest('ask_time')
        a_content = a.question_content
        a_content = ' '.join([word for word in a_content.split() if word not in StopWords])
    except Question.DoesNotExist:
        a = None
    count = 0
    for questions in all_questions_with_sub_code:
        b = questions.question_content
        b = ' '.join([word for word in b.split() if word not in StopWords])
        similarity = SequenceMatcher(None, a_content, b).ratio()
        if similarity >= 0.5:
            similar_questions.append(questions)
            count += 1
    if similar_questions:
        similar_questions.pop()
    if count > 1:
        Question.objects.filter(sub_code=sub_code).latest('ask_time').delete()
    context = {
        'similar_questions': similar_questions,
        'sub_code': sub_code
    }
    return render(request, 'courses/course_similar.html', context)


def course_question(request, sub_code):
    form = QuestionForm()
    if request.method == 'POST':
        form = QuestionForm(request.POST)
        if form.is_valid():
            question = Question()
            question.question_title = form.data['question_title']
            question.question_content = form.data['question_content']
            question.sub_code = sub_code
            question.author = request.user
            question.ask_time = datetime.datetime.now()
            question.save()
            return redirect("../../" + sub_code + "_similar")
    context = {
        'form': form,
        'sub_code': sub_code
    }
    return render(request, 'courses/course_question.html', context)


def about(request):
    form = SignInForm(request.POST or None)
    if not request.user.is_authenticated():
        return render(request, 'html_pages/login.html', {"form": form})
    else:
        return render(request, 'html_pages/about.html')


def ask(request):
    form = SignInForm(request.POST or None)
    if not request.user.is_authenticated():
        return render(request, 'html_pages/login.html', {"form": form})
    else:
        return render(request, 'html_pages/ask.html')


def logout_user(request):
    logout(request)
    form = SignInForm(request.POST or None)
    context = {
        "form": form,
    }
    return render(request, 'html_pages/login.html', context)


def login_user(request):
    form = SignInForm(request.POST or None)
    if request.method == "POST":
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(username=username, password=password)
        if user is not None:
            if user.is_active:
                login(request, user)
                return render(request, 'html_pages/ask.html')
            else:
                return render(request, 'html_pages/login.html', {'error_message': 'Your account has been disabled',
                                                                 'form': form})
        else:
            return render(request, 'html_pages/login.html', {'error_message': 'Invalid login',
                                                             'form': form})
    return render(request, 'html_pages/login.html', {'form': form})


def register(request):
    form = UserForm(request.POST or None)
    signinform = SignInForm(request.POST or None)
    if form.is_valid():
        user = form.save(commit=False)
        username = form.cleaned_data['username']
        password = form.cleaned_data['password']
        user.set_password(password)
        user.save()
        user = authenticate(username=username, password=password)
        if user is not None:
            if user.is_active:
                login(request, user)
                return render(request, 'html_pages/login.html', {"form": signinform})
    context = {
        "form": form,
    }
    return render(request, 'html_pages/register.html', context)


def answer(request):
    form = SignInForm(request.POST or None)
    if not request.user.is_authenticated():
        return render(request, 'html_pages/login.html', {"form": form})
    else:
        return render(request, 'html_pages/answer.html')

Pekka 2.0/pekka/templates/html_pages/answer.html
{% extends 'html_pages/base.html' %}
{% block title %}Answer{% endblock %}
{% block answer_active %}active{% endblock %}

{% block body %}
<div class="container-fluid">
    <div class="row">
        <div class="col-sm-12">
            <div class="panel panel-primary">
                <div class="panel-heading">
                    <h3 class="panel-title"><b>Find your subject's code and answer questions to help your classmates out!</b></h3>
                </div>
                <div class="panel-body">
                    <table class="table table-striped table-hover">
                        <thead>
                            <tr>
                                <th class="col-sm-1">Code</th>
                                <th class="col-sm">Course Name</th>
                            </tr>
                        </thead>
                        <tbody>
                            <tr class="clickable_row" data-href="{% url 'pekka:TDT4140_answer' %}">
                                <td>TDT4140</td>
                                <td>Software Engineering</td>
                            </tr>
                            <tr class="clickable_row" data-href="{% url 'pekka:TDT4145_answer' %}">
                                <td>TDT4145</td>
                                <td>Data Modelling, Databases and Database Management Systems</td>
                            </tr>
                            <tr class="clickable_row" data-href="{% url 'pekka:TDT4180_answer' %}">
                                <td>TDT4180</td>
                                <td>Human-Computer Interaction</td>
                            </tr>
                            <tr class="clickable_row" data-href="{% url 'pekka:TTM4100_answer' %}">
                                <td>TTM4100</td>
                                <td>Communication - Services and Networks</td>
                            </tr>
                            <tr class="clickable_row" data-href="{% url 'pekka:TDT4110_answer' %}">
                                <td>TDT4110</td>
                                <td>Information Technology, Introduction</td>
                            </tr>
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

Pekka 2.0/pekka/templates/html_pages/ask.html
{% extends 'html_pages/base.html' %}
{% block title %}Ask{% endblock %}
{% block ask_active %}active{% endblock %}

{% block body %}
<div class="container-fluid">
    <div class="row">
        <div class="col-sm-12">
            <div class="panel panel-primary">
                <div class="panel-heading">
                    <h3 class="panel-title"><b>Find your subject and ask away!</b></h3>
                </div>
                <div class="panel-body">
                                        <table class="table table-striped table-hover">
                        <thead>
                            <tr>
                                <th class="col-sm-1">Code</th>
                                <th class="col-sm">Course Name</th>
                            </tr>
                        </thead>
                        <tbody>
                            <tr class="clickable_row" data-href="{% url 'pekka:TDT4140_question' %}">
                                <td>TDT4140</td>
                                <td>Software Engineering</td>
                            </tr>
                            <tr class="clickable_row" data-href="{% url 'pekka:TDT4145_question' %}">
                                <td>TDT4145</td>
                                <td>Data Modelling, Databases and Database Management Systems</td>
                            </tr>
                            <tr class="clickable_row" data-href="{% url 'pekka:TDT4180_question' %}">
                                <td>TDT4180</td>
                                <td>Human-Computer Interaction</td>
                            </tr>
                            <tr class="clickable_row" data-href="{% url 'pekka:TTM4100_question' %}">
                                <td>TTM4100</td>
                                <td>Communication - Services and Networks</td>
                            </tr>
                            <tr class="clickable_row" data-href="{% url 'pekka:TDT4110_question' %}">
                                <td>TDT4110</td>
                                <td>Information Technology, Introduction</td>
                            </tr>
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

Pekka 2.0/pekka/templates/html_pages/base.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <title>{% block title %}{% endblock %}</title>
        {% load staticfiles %}
        <link rel="shortcut icon" type="image/png" href="{%  static 'p_icon.png' %}"/>
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
        <link href='https://fonts.googleapis.com/css?family=Satisfy' rel='stylesheet' type='text/css'>
        <link rel="stylesheet" type="text/css" href="{% static 'elements/style.css' %}"/>
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
        <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
        <script src="{% static 'elements/js/main.js' %}"></script>
    </head>
    <body>
        <nav class="navbar navbar-inverse">
            <div class="container-fluid">

                <!-- Header -->
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#topNavBar">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand" href="{% url 'pekka:ask' %}">Pekka 2.0</a>
                </div>

                <!-- Items -->
                <div class="collapse navbar-collapse" id="topNavBar">
                    <!-- Navbar left -->
                    <ul class="nav navbar-nav">
                        <li class="{% block answer_active %}{% endblock %}"><a href="{% url 'pekka:answer' %}">
                            <span class="glyphicon glyphicon-pencil" aria-hidden="true"></span>&nbsp; Answer</a>
                        </li>
                        <li class="{% block ask_active %}{% endblock %}"><a href="{% url 'pekka:ask' %}">
                            <span class="glyphicon glyphicon-question-sign" aria-hidden="true"></span>&nbsp; Ask</a>
                        </li>
                    </ul>
                    <!-- Navbar right -->
                    <ul class="nav navbar-nav navbar-right">
                        <li class="{% block about_active %}{% endblock %}"><a href="{% url 'pekka:about' %}">
                                <span class="glyphicon glyphicon-info-sign" aria-hidden="true"></span>&nbsp; About</a>
                        </li>
                        <li><a href="{% url 'pekka:logout_user' %}">
                                <span class="glyphicon glyphicon-off" aria-hidden="true"></span>&nbsp; Sign out</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
        {% block body %}
        {% endblock %}
    </body>
</html>

Pekka 2.0/pekka/templates/html_pages/base_visitor.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <title>{% block title %}Pekka 2.0{% endblock %}</title>
        {% load staticfiles %}
        <link rel="shortcut icon" type="image/png" href="{%  static 'p_icon.png' %}"/>
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
        <link href='https://fonts.googleapis.com/css?family=Satisfy' rel='stylesheet' type='text/css'>
        <link rel="stylesheet" type="text/css" href="{% static 'elements/style.css' %}"/>
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
        <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
        <script src="{% static 'elements/js/main.js' %}"></script>
    </head>
    <body>
        <nav class="navbar navbar-inverse">
            <div class="container-fluid">

                <!-- Header -->
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#topNavBar">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand" href="{% url 'pekka:login_user' %}">Pekka 2.0</a>
                </div>

                <!-- Items -->
                <div class="collapse navbar-collapse" id="topNavBar">
                    <!-- Navbar left -->
                    <ul class="nav navbar-nav">
                        <li class="{% block register_active %}{% endblock %}"><a href="{% url 'pekka:register' %}">
                            <span class="glyphicon glyphicon-user" aria-hidden="true"></span>&nbsp; Register</a>
                        </li>
                        <li class="{% block login_active %}{% endblock %}"><a href="{% url 'pekka:login_user' %}">
                            <span class="glyphicon glyphicon-education" aria-hidden="true"></span>&nbsp; Sign in</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
        {% block body %}
        {% endblock %}
    </body>
</html>

Pekka 2.0/pekka/templates/html_pages/detail.html
{% extends 'html_pages/base.html' %}
{% block title %}{{ question }}{% endblock %}

<!-- SVAR SORTERES ETTER SCORE -->
{% block body %}
<div class="container-fluid">
    <div class="row">
        <div class="col-sm-4">
            <div class="panel panel-primary">
                <div class="panel-heading">
                    <h3 class="panel-title"><b>{{ sub_code }} - Question</b></h3>
                </div>
                <div class="panel-body">
                    <p>Rate this question by clicking on its score!</p>
                    <h4>Score <a href="vote_question/"><span class="badge titlebadge" id="titlebadge">{{score}}</span></a></h4>
                    <div class="well">
                        <div id="title">{{ question_title }}</div>
                        {{ question_content }}
                    </div>
                    <a href="/{{ sub_code }}_answer"><button class="btn btn-default center-block">Back to questions in {{sub_code}}</button></a>
                </div>
            </div>
        </div>
        <div class="col-sm-4">
            <div class="panel panel-primary">
                <div class="panel-heading">
                    <h3 class="panel-title"><b>Answers</b></h3>
                </div>
                <div class="panel-body">
                    <p>Rate answers by clicking on their score!</p>
                    {% for answer in answers|dictsortreversed:"get_score" %}
                        <div class="well well-sm">
                            <h4>Score <a href="{% url 'pekka:vote_answer' answer.id %}">
                                <span class="badge answerbadge" id="answerbadge"><b>{{answer.get_score}}</b></span></a></h4>
                            <p class="para">{{ answer.answer_text }}</p>
                            <p style="font-size:12px" class="text-right para"><i>Answered by {{answer.author}} </i>
                                <span class="badge answerbybadge" id="answerbybadge">{{answer.get_author_rating}}</span></p>
                        </div>
                    {% endfor %}
                </div>
            </div>
        </div>
        <div class="col-sm-4">
            <div class="panel panel-primary">
                <div class="panel-heading">
                    <h3 class="panel-title"><b>Write a new answer</b></h3>
                </div>
                <div class="panel-body">
                    <form class="form-horizontal" role="form" action="" method="post">
                        {% csrf_token %}
                        {% include 'html_pages/form_template.html' %}
                        <button type="submit" class="btn btn-success center-block">Submit</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
<script>
    window.addEventListener('load', function() {
        //titlebadge
        var q_score = {{ score }};
        var q_elmt = document.getElementById('titlebadge');

        if (q_score < 0) {
            q_elmt.style.backgroundColor = "#D9534F";
        }
        else if (q_score > 0) {
            q_elmt.style.backgroundColor = "#5CB85C";
        }
        else {
            q_elmt.style.backgroundColor = "#777777";
        }

        //answerbadge and answeredbybadge
        var i = 1;
        {% for answer in answers|dictsortreversed:"get_score" %}
            var a_score = {{ answer.get_score }};
            document.getElementById('answerbadge').id = 'answerbadge' + i;
            var a_elmt = document.getElementById('answerbadge' + i);

            var ab_score = {{ answer.get_author_rating }}
            document.getElementById('answerbybadge').id = 'answerbybadge' + i;
            var ab_elmt = document.getElementById('answerbybadge' + i);

            if (a_score < 0) {
                a_elmt.style.backgroundColor = "#D9534F";
            }
            else if (a_score > 0) {
                a_elmt.style.backgroundColor = "#5CB85C";
            }
            else {
                a_elmt.style.backgroundColor = "#777777";
            }

            if (ab_score < 0) {
                ab_elmt.style.backgroundColor = "#D9534F";
            }
            else if (ab_score > 0) {
                ab_elmt.style.backgroundColor = "#5CB85C";
            }
            else {
                ab_elmt.style.backgroundColor = "#777777";
            }
            i += 1;
        {% endfor %}
    });
</script>
{% endblock %}

Pekka 2.0/pekka/templates/html_pages/form_template.html
{% for field in form %}
    <div class="form-group">
        <label class="control-label">
            {{ field.label_tag }}
        </label>
        <div class="col-sm-12">
            {{ field }}
        </div>
    </div>
{% endfor %}

Pekka 2.0/pekka/templates/html_pages/login.html
{% extends 'html_pages/base_visitor.html' %}
{% block title %}Sign in{% endblock %}
{% block login_active %}active{% endblock %}

{% block body %}
<div class="container-fluid centerpanel">
    <div class="row">
        <div class="col-sm-12">
            <div class="panel panel-primary">
                <div class="panel-heading">
                    <h3 class="panel-title"><b>Sign in</b></h3>
                </div>
                <div class="panel-body">
                    {% if error_message %}
                        <div class="alert alert-danger" role="alert" align="center"><p><strong>{{ error_message }}</strong></p></div>
                    {% endif %}
                    <form class="form-horizontal" role="form" action="{% url 'pekka:login_user'%}" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        {% include 'html_pages/form_template.html' %}
                        <button type="submit" class="btn btn-success center-block">Submit</button>
                    </form>
                </div>
                <div class="panel-footer">
                    Don't have an account? <a href="{% url 'pekka:register' %}">Click here</a> to register.
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}