Pekka 2.0/pekka/urls.py
from django.conf.urls import url
from . import views

app_name = 'pekka'

urlpatterns = [
    # login and register
    url(r'^$', views.login_user, name='login_user'),
    url(r'^login_user/$', views.login_user, name='login_user'),
    url(r'^register/$', views.register, name='register'),
    url(r'^logout_user/$', views.logout_user, name='logout_user'),
    # main views
    url(r'^ask/$', views.ask, name='ask'),
    url(r'^answer/$', views.answer, name='answer'),
    url(r'^about/$', views.about, name='about'),
    # question and voting
    url(r'^(?P<question_id>[0-9]+)/$', views.detail, name='detail'),
    url(r'^(?P<answer_id>[0-9]+)/vote_answer/$', views.vote_answer, name='vote_answer'),
    url(r'^(?P<question_id>[0-9]+)/vote_question/$', views.vote_question, name='vote_question'),
    # courses
    url(r'^TDT4140_answer/$', views.course_answer, {'sub_code': 'TDT4140'}, name='TDT4140_answer'),
    url(r'^TDT4110_answer/$', views.course_answer, {'sub_code': 'TDT4110'}, name='TDT4110_answer'),
    url(r'^TDT4145_answer/$', views.course_answer, {'sub_code': 'TDT4145'}, name='TDT4145_answer'),
    url(r'^TDT4180_answer/$', views.course_answer, {'sub_code': 'TDT4180'}, name='TDT4180_answer'),
    url(r'^TTM4100_answer/$', views.course_answer, {'sub_code': 'TTM4100'}, name='TTM4100_answer'),

    url(r'^TDT4140_question/$', views.course_question, {'sub_code': 'TDT4140'}, name='TDT4140_question'),
    url(r'^TDT4110_question/$', views.course_question, {'sub_code': 'TDT4110'}, name='TDT4110_question'),
    url(r'^TDT4145_question/$', views.course_question, {'sub_code': 'TDT4145'}, name='TDT4145_question'),
    url(r'^TDT4180_question/$', views.course_question, {'sub_code': 'TDT4180'}, name='TDT4180_question'),
    url(r'^TTM4100_question/$', views.course_question, {'sub_code': 'TTM4100'}, name='TTM4100_question'),

    url(r'^TDT4140_similar/$', views.course_similar, {'sub_code': 'TDT4140'}, name='TDT4140_similar'),
    url(r'^TDT4110_similar/$', views.course_similar, {'sub_code': 'TDT4110'}, name='TDT4110_similar'),
    url(r'^TDT4145_similar/$', views.course_similar, {'sub_code': 'TDT4145'}, name='TDT4145_similar'),
    url(r'^TDT4180_similar/$', views.course_similar, {'sub_code': 'TDT4180'}, name='TDT4180_similar'),
    url(r'^TTM4100_similar/$', views.course_similar, {'sub_code': 'TTM4100'}, name='TTM4100_similar')
]

Pekka 2.0/website/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^pekka/', include('pekka.urls')),
    url(r'^', include('pekka.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Pekka 2.0/pekka/forms.py
from django import forms
from .models import *


class QuestionForm(forms.Form):

    question_title = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control'}), help_text="")
    question_content = forms.CharField(widget=forms.Textarea(attrs={'cols': 30,
                                                                    'rows': 10,
                                                                    'class': 'form-control'}), help_text="")

    class Meta:
        model = Question
        fields = ('question_title', 'question_content')


class AnswerForm(forms.Form):

    answer_text = forms.CharField(widget=forms.Textarea(attrs={'cols': 30,
                                                               'rows': 10,
                                                               'class': 'form-control'}), help_text="")

    class Meta:
        model = Answer
        fields = 'answer_text'


class QuestionVotesForm(forms.ModelForm):
    UP = '+1'
    REMOVE = '0'
    DOWN = '-1'
    CHOICES = ((UP, 'Upvote'), (REMOVE, 'Remove vote'), (DOWN, 'Downvote'))
    #    CHOICES = ('+1', '0', '-1')
    val = forms.ChoiceField(label="", choices=CHOICES, widget=forms.RadioSelect(), help_text="Don't forget to submit!")

    class Meta:
        model = QuestionVotes
        exclude = ('question', 'user', 'val')


class AnswerVotesForm(forms.ModelForm):
    CHOICES = (('+1', 'Upvote'), ('0', 'Remove vote'), ('-1', 'Downvote'))
    #    CHOICES = ('+1', '0', '-1')
    val = forms.ChoiceField(label="", choices=CHOICES, widget=forms.RadioSelect(), help_text="Don't forget to submit!")

    class Meta:
        model = AnswerVotes
        exclude = ('ans', 'user', 'val')


class UserForm(forms.ModelForm):

    username = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control'}), help_text="")
    email = forms.CharField(widget=forms.EmailInput(attrs={'class': 'form-control'}), help_text="")
    password = forms.CharField(widget=forms.PasswordInput(attrs={'class': 'form-control'}), help_text="")

    class Meta:
        model = User
        fields = ['username', 'email', 'password']


class SignInForm(forms.ModelForm):

    username = forms.CharField(max_length=30, widget=forms.TextInput(attrs={'class': 'form-control'}), help_text="")
    password = forms.CharField(max_length=30, widget=forms.PasswordInput(attrs={'class': 'form-control'}), help_text="")

    class Meta:
        model = User
        fields = ['username', 'password']

Pekka 2.0/pekka/views.py
from django.contrib.auth import authenticate, login
from django.contrib.auth import logout
from django.http import HttpResponseRedirect,  Http404
from django.shortcuts import render
from . forms import *
from .models import *
import datetime
from difflib import SequenceMatcher
from django.shortcuts import redirect


# Adding a StopWord list to avoid comparing insignificant words
StopWords = ['is', 'when', 'what', 'the', 'and', 'where', '?', ' ',
             'should', 'can', 'I', 'i', 'a', 'an', 'are',
             'why', 'how', 'be', 'but', 'if', 'for', 'in',
             'it', 'of', 'or', 'so', 'to', 'about', 'on', "we", 'us']


# Detail is the detailed view of a single question, with associated answers.
def detail(request, question_id):
    try:
        question = Question.objects.get(pk=question_id)
        answers = question.answer_set.all()
        score = question.get_score()
        form = AnswerForm(request.POST)
        if request.method == 'POST':
            if form.is_valid():
                answer = Answer()
                answer.answer_text = form.data['answer_text']
                answer.author = request.user
                answer.answer_time = datetime.datetime.now()
                answer.question = question
                answer.save()
                form = AnswerForm()
                return render(request, 'html_pages/detail.html', {'score': score,
                                                                  'question_title': question.question_title,
                                                                  'question_content': question.question_content,
                                                                  'sub_code': question.sub_code,
                                                                  'answers': answers,
                                                                  'form': form
                                                                  })
    except Question.DoesNotExist:
        raise Http404("Question does not exist")
    return render(request, 'html_pages/detail.html', {'score': score,
                                                      'question_title': question.question_title,
                                                      'question_content': question.question_content,
                                                      'sub_code': question.sub_code,
                                                      'answers': answers,
                                                      'form': form
                                                      })


def vote_question(request, question_id):
    question = Question.objects.get(pk=question_id)
    form = QuestionVotesForm()
    previous_page = request.META.get('HTTP_REFERER')
    if request.method == 'POST':
        form = QuestionVotesForm(request.POST)
        if form.is_valid():
            qv = QuestionVotes()
            qv.user = request.user
            qv.question = question
            qv.val = form.data['val']
            if not QuestionVotes.objects.filter(question=qv.question, user=qv.user):
                qv.save()
            else:
                existing_votes = QuestionVotes.objects.filter(question=question, user=qv.user)
                for vote in existing_votes:
                    vote.delete()
                qv.save()
            return HttpResponseRedirect('/' + question_id)
    return render(request, template_name='html_pages/vote_question.html', context={
            'question_id': question_id,
            'question_title': question.question_title,
            'question_content': question.question_content,
            'score': question.get_score(),
            'form': form,
            'previous_page': previous_page
            })


def vote_answer(request, answer_id):
    answer = Answer.objects.get(pk=answer_id)
    form = AnswerVotesForm()
    current_score = answer.get_score()
    if request.method == 'POST':
        form = AnswerVotesForm(request.POST)
        if form.is_valid():
            answ = AnswerVotes()
            answ.user = request.user
            answ.ans = answer
            answ.val = form.data['val']
            if not AnswerVotes.objects.filter(ans=answer, user=answ.user):
                answ.save()
            else:
                existing_votes = AnswerVotes.objects.filter(ans=answer, user=answ.user)
                for vote in existing_votes:
                    vote.delete()
                answ.save()
            return HttpResponseRedirect('/' + str(answer.question.id))
    return render(request, template_name='html_pages/vote_answer.html', context={
            'question': answer.question,
            'answer': answer,
            'score': current_score,
            'form': form
            })
# ------------------------------------------------------------------------------------------------------------------


def course_answer(request, sub_code):
    all_questions_with_sub_code = Question.objects.filter(sub_code=sub_code)
    context = {
        'all_questions_with_sub_code': all_questions_with_sub_code,
        'sub_code': sub_code
    }
    return render(request, 'courses/course_answer.html', context=context)


def course_similar(request, sub_code):
    all_questions_with_sub_code = Question.objects.filter(sub_code=sub_code)
    similar_questions = []
    try:
        a = Question.objects.filter(sub_code=sub_code).latest('ask_time')
        a_content = a.question_content
        a_content = ' '.join([word for word in a_content.split() if word not in StopWords])
    except Question.DoesNotExist:
        a = None
    count = 0
    for questions in all_questions_with_sub_code:
        b = questions.question_content
        b = ' '.join([word for word in b.split() if word not in StopWords])
        similarity = SequenceMatcher(None, a_content, b).ratio()
        if similarity >= 0.5:
            similar_questions.append(questions)
            count += 1
    if similar_questions:
        similar_questions.pop()
    if count > 1:
        Question.objects.filter(sub_code=sub_code).latest('ask_time').delete()
    context = {
        'similar_questions': similar_questions,
        'sub_code': sub_code
    }
    return render(request, 'courses/course_similar.html', context)


def course_question(request, sub_code):
    form = QuestionForm()
    if request.method == 'POST':
        form = QuestionForm(request.POST)
        if form.is_valid():
            question = Question()
            question.question_title = form.data['question_title']
            question.question_content = form.data['question_content']
            question.sub_code = sub_code
            question.author = request.user
            question.ask_time = datetime.datetime.now()
            question.save()
            return redirect("../../" + sub_code + "_similar")
    context = {
        'form': form,
        'sub_code': sub_code
    }
    return render(request, 'courses/course_question.html', context)


def about(request):
    form = SignInForm(request.POST or None)
    if not request.user.is_authenticated():
        return render(request, 'html_pages/login.html', {"form": form})
    else:
        return render(request, 'html_pages/about.html')


def ask(request):
    form = SignInForm(request.POST or None)
    if not request.user.is_authenticated():
        return render(request, 'html_pages/login.html', {"form": form})
    else:
        return render(request, 'html_pages/ask.html')


def logout_user(request):
    logout(request)
    form = SignInForm(request.POST or None)
    context = {
        "form": form,
    }
    return render(request, 'html_pages/login.html', context)


def login_user(request):
    form = SignInForm(request.POST or None)
    if request.method == "POST":
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(username=username, password=password)
        if user is not None:
            if user.is_active:
                login(request, user)
                return render(request, 'html_pages/ask.html')
            else:
                return render(request, 'html_pages/login.html', {'error_message': 'Your account has been disabled',
                                                                 'form': form})
        else:
            return render(request, 'html_pages/login.html', {'error_message': 'Invalid login',
                                                             'form': form})
    return render(request, 'html_pages/login.html', {'form': form})


def register(request):
    form = UserForm(request.POST or None)
    signinform = SignInForm(request.POST or None)
    if form.is_valid():
        user = form.save(commit=False)
        username = form.cleaned_data['username']
        password = form.cleaned_data['password']
        user.set_password(password)
        user.save()
        user = authenticate(username=username, password=password)
        if user is not None:
            if user.is_active:
                login(request, user)
                return render(request, 'html_pages/login.html', {"form": signinform})
    context = {
        "form": form,
    }
    return render(request, 'html_pages/register.html', context)


def answer(request):
    form = SignInForm(request.POST or None)
    if not request.user.is_authenticated():
        return render(request, 'html_pages/login.html', {"form": form})
    else:
        return render(request, 'html_pages/answer.html')

Pekka 2.0/pekka/templates/courses/TTM4100_a.html
{% extends 'html_pages/base.html' %}

<!-- SPØRSMÅL SORTERES etter ønsket attr., feks. [ "ask_time" eller "get_score" ]-->

{% block title %}TTM4100{% endblock %}

{% block body %}
<div class="container-fluid">
    <div class="row">
        <div class="col-sm-12">
            {% if all_questions_with_sub_code %}
                <div class="panel panel-primary">
                    <div class="panel-heading">
                        <h3 class="panel-title"><b>Here are all questions asked in this subject</b></h3>
                    </div>
                    <div class="panel-body">
                        <table class="table table-striped table-hover">
                            <thead>
                            <tr>
                                <th class="col-sm-1">#</th>
                                <th class="col-sm-3">Question title</th>
                                <th class="col-sm">Score</th>
                            </tr>
                            </thead>
                            <tbody>
                            {% for question in all_questions_with_sub_code|dictsortreversed:"get_score" %}
                                <tr class="clickable_row" data-href="{% url 'pekka:detail' question.id %}">
                                    <td>{{ question.id }}</td>
                                    <td>{{ question.question_title }}</td>
                                    <td><span class="badge tablebadge" id="tablebadge">{{ question.get_score }}</span></td>
                                </tr>
                            {% endfor %}
                            </tbody>
                        </table>
                    </div>
                </div>
            {% else %}
                <div class="col-sm-4">
                    <div class="alert alert-danger" role="alert" align="center">
                        <p><strong>There are no questions asked in this subject yet</strong></p>
                    </div>
                </div>
            {% endif %}
        </div>
    </div>
</div>
<script>
    window.addEventListener('load', function() {
        console.log('her');
        var i = 1;
        {% for question in all_questions_with_sub_code|dictsortreversed:"get_score" %}
            var q_score = {{ question.get_score }};
            document.getElementById('tablebadge').id = 'tablebadge' + i;
            var q_elmt = document.getElementById('tablebadge' + i);

            if (q_score < 0) {
                q_elmt.style.backgroundColor = "#D9534F";
            }
            else if (q_score > 0) {
                q_elmt.style.backgroundColor = "#5CB85C";
            }
            else {
                q_elmt.style.backgroundColor = "#777777";
            }
            i += 1;
        {% endfor %}
    });
</script>
{% endblock %}

Pekka 2.0/pekka/templates/courses/TTM4100_b.html
{% extends 'html_pages/base.html' %}

{% block title %}TTM4100{% endblock %}

{% block body %}
<div class="container-fluid">
    <div class="row">
        <div class="col-sm-12">
            {% if similar_questions %}
                <div class="panel panel-primary">
                    <div class="panel-heading">
                        <h3 class="panel-title"><b>Potentially similar questions that are already asked</b></h3>
                    </div>
                    <div class="panel-body">
                        <table class="table table-striped table-hover">
                            <thead>
                            <tr>
                                <th class="col-sm-1">#</th>
                                <th class="col-sm-3">Question title</th>
                                <th class="col-sm">Score</th>
                            </tr>
                            </thead>
                            <tbody>
                            {% for question in similar_questions %}
                                <tr class="clickable_row" data-href="{% url 'pekka:detail' question.id %}">
                                    <td>{{ question.id }}</td>
                                    <td>{{ question.question_title }}</td>
                                    <td><span class="badge tablebadge" id="tablebadge">{{ question.get_score }}</span></td>
                                </tr>
                            {% endfor %}
                            </tbody>
                        </table>
                    </div>
                </div>
            {% else %}
                <div class="col-sm-5 centerpanel">
                    <div class="alert alert-danger" role="alert" align="center">
                        <p><strong>There are no questions asked on your specific topic in this subject yet</strong></p>
                    </div>
                    <a href="/{{ sub_code }}_a"><button class="btn btn-default center-block">See other questions in this subject</button></a>
                </div>
            {% endif %}
        </div>
    </div>
</div>
<script>
    window.addEventListener('load', function() {
        var i = 1;
        {% for question in similar_questions %}
            var q_score = {{ question.get_score }};
            document.getElementById('tablebadge').id = 'tablebadge' + i;
            var q_elmt = document.getElementById('tablebadge' + i);
            if (q_score < 0) {
                q_elmt.style.backgroundColor = "#D9534F";
            }
            else if (q_score > 0) {
                q_elmt.style.backgroundColor = "#5CB85C";
            }
            else {
                q_elmt.style.backgroundColor = "#777777";
            }
            i += 1;
        {% endfor %}
    });
</script>
{% endblock %}

Pekka 2.0/pekka/templates/courses/TTM4100_q.html
{% extends 'html_pages/base.html' %}

{% block title %}TTM4100{% endblock %}

{% block body %}
<div class="container-fluid centerpanel">
    <div class="row">
        <div class="col-sm-12">
            <div class="panel panel-primary">
                <div class="panel-heading">
                    <h3 class="panel-title"><b>Ask a new question</b></h3>
                </div>
                <div class="panel-body">
                    <form class="form-horizontal" role="form" action="" method="post">
                        {% csrf_token %}
                        {% include 'html_pages/form_template.html' %}
                        <button type="submit" class="btn btn-success center-block">Submit</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

Pekka 2.0/pekka/templates/courses/course_a.html
{% extends 'html_pages/base.html' %}

<!-- SPØRSMÅL SORTERES etter ønsket attr., feks. [ "ask_time" eller "get_score" ]-->

{% block title %}{{ sub_code }}{% endblock %}

{% block body %}
<div class="container-fluid">
    <div class="row">
        <div class="col-sm-12">
            {% if all_questions_with_sub_code %}
                <div class="panel panel-primary">
                    <div class="panel-heading">
                        <h3 class="panel-title"><b>{{ sub_code }} - All questions</b></h3>
                    </div>
                    <div class="panel-body">
                        <table class="table table-striped table-hover">
                            <thead>
                            <tr>
                                <th class="col-sm-1">ID</th>
                                <th class="col-sm-3">Question title</th>
                                <th class="col-sm-5">Question content</th>
                                <th class="col-sm">Score</th>
                            </tr>
                            </thead>
                            <tbody>
                            {% for question in all_questions_with_sub_code|dictsortreversed:"get_score" %}
                                <tr class="clickable_row" data-href="{% url 'pekka:detail' question.id %}">
                                    <td>{{ question.id }}</td>
                                    <td>{{ question.question_title }}</td>
                                    <td>{{ question.question_content }}</td>
                                    <td><span class="badge tablebadge" id="tablebadge">{{ question.get_score }}</span></td>
                                </tr>
                            {% endfor %}
                            </tbody>
                        </table>
                    </div>
                </div>
            {% else %}
                <div class="col-sm-4 centerpanel">
                    <div class="alert alert-danger" role="alert" align="center">
                        <p><strong>There are no questions asked in this subject yet</strong></p>
                    </div>
                </div>
            {% endif %}
        </div>
    </div>
</div>
<script>
    window.addEventListener('load', function() {
        console.log('her');
        var i = 1;
        {% for question in all_questions_with_sub_code|dictsortreversed:"get_score" %}
            var q_score = {{ question.get_score }};
            document.getElementById('tablebadge').id = 'tablebadge' + i;
            var q_elmt = document.getElementById('tablebadge' + i);

            if (q_score < 0) {
                q_elmt.style.backgroundColor = "#D9534F";
            }
            else if (q_score > 0) {
                q_elmt.style.backgroundColor = "#5CB85C";
            }
            else {
                q_elmt.style.backgroundColor = "#777777";
            }
            i += 1;
        {% endfor %}
    });
</script>
{% endblock %}

Pekka 2.0/pekka/templates/courses/course_answer.html
{% extends 'html_pages/base.html' %}

<!-- SPØRSMÅL SORTERES etter ønsket attr., feks. [ "ask_time" eller "get_score" ]-->

{% block title %}{{ sub_code }}{% endblock %}

{% block body %}
<div class="container-fluid">
    <div class="row">
        <div class="col-sm-12">
            {% if all_questions_with_sub_code %}
                <div class="panel panel-primary">
                    <div class="panel-heading">
                        <h3 class="panel-title"><b>{{ sub_code }} - All questions</b></h3>
                    </div>
                    <div class="panel-body">
                        <table class="table table-striped table-hover">
                            <thead>
                            <tr>
                                <th class="col-sm-1">ID</th>
                                <th class="col-sm-3">Question title</th>
                                <th class="col-sm-5">Question content</th>
                                <th class="col-sm">Score</th>
                            </tr>
                            </thead>
                            <tbody>
                            {% for question in all_questions_with_sub_code|dictsortreversed:"get_score" %}
                                <tr class="clickable_row" data-href="{% url 'pekka:detail' question.id %}">
                                    <td>{{ question.id }}</td>
                                    <td>{{ question.question_title }}</td>
                                    <td>{{ question.question_content }}</td>
                                    <td><span class="badge tablebadge" id="tablebadge">{{ question.get_score }}</span></td>
                                </tr>
                            {% endfor %}
                            </tbody>
                        </table>
                    </div>
                </div>
            {% else %}
                <div class="col-sm-4 centerpanel">
                    <div class="alert alert-danger" role="alert" align="center">
                        <p><strong>There are no questions asked in this subject yet</strong></p>
                    </div>
                </div>
            {% endif %}
        </div>
    </div>
</div>
<script>
    window.addEventListener('load', function() {
        console.log('her');
        var i = 1;
        {% for question in all_questions_with_sub_code|dictsortreversed:"get_score" %}
            var q_score = {{ question.get_score }};
            document.getElementById('tablebadge').id = 'tablebadge' + i;
            var q_elmt = document.getElementById('tablebadge' + i);

            if (q_score < 0) {
                q_elmt.style.backgroundColor = "#D9534F";
            }
            else if (q_score > 0) {
                q_elmt.style.backgroundColor = "#5CB85C";
            }
            else {
                q_elmt.style.backgroundColor = "#777777";
            }
            i += 1;
        {% endfor %}
    });
</script>
{% endblock %}

Pekka 2.0/pekka/templates/courses/course_b.html
{% extends 'html_pages/base.html' %}

{% block title %}{{ sub_code }}{% endblock %}

{% block body %}
<div class="container-fluid">
    <div class="row">
        <div class="col-sm-12">
            {% if similar_questions %}
                <div class="panel panel-primary">
                    <div class="panel-heading">
                        <h3 class="panel-title"><b>{{ sub_code }} - Potentially similar questions</b></h3>
                    </div>
                    <div class="panel-body">
                        <table class="table table-striped table-hover">
                            <thead>
                            <tr>
                                <th class="col-sm-1">ID</th>
                                <th class="col-sm-3">Question title</th>
                                <th class="col-sm-5">Question content</th>
                                <th class="col-sm">Score</th>
                            </tr>
                            </thead>
                            <tbody>
                            {% for question in similar_questions %}
                                <tr class="clickable_row" data-href="{% url 'pekka:detail' question.id %}">
                                    <td>{{ question.id }}</td>
                                    <td>{{ question.question_title }}</td>
                                    <td>{{ question.question_content }}</td>
                                    <td><span class="badge tablebadge" id="tablebadge">{{ question.get_score }}</span></td>
                                </tr>
                            {% endfor %}
                            </tbody>
                        </table>
                    </div>
                </div>
            {% else %}
                <div class="col-sm-5 centerpanel">
                    <div class="alert alert-danger" role="alert" align="center">
                        <p><strong>There are no questions asked on your specific topic in this subject yet</strong></p>
                    </div>
                    <a href="../{{ sub_code }}_a"><button class="btn btn-default center-block">See other questions in this subject</button></a>
                </div>
            {% endif %}
        </div>
    </div>
</div>
<script>
    window.addEventListener('load', function() {
        var i = 1;
        {% for question in similar_questions %}
            var q_score = {{ question.get_score }};
            document.getElementById('tablebadge').id = 'tablebadge' + i;
            var q_elmt = document.getElementById('tablebadge' + i);
            if (q_score < 0) {
                q_elmt.style.backgroundColor = "#D9534F";
            }
            else if (q_score > 0) {
                q_elmt.style.backgroundColor = "#5CB85C";
            }
            else {
                q_elmt.style.backgroundColor = "#777777";
            }
            i += 1;
        {% endfor %}
    });
</script>
{% endblock %}

Pekka 2.0/pekka/templates/courses/course_q.html
{% extends 'html_pages/base.html' %}

{% block title %}{{ sub_code }}{% endblock %}

{% block body %}
<div class="container-fluid centerpanel">
    <div class="row">
        <div class="col-sm-12">
            <div class="panel panel-primary">
                <div class="panel-heading">
                    <h3 class="panel-title"><b>{{ sub_code }} - Ask a new question</b></h3>
                </div>
                <div class="panel-body">
                    <form class="form-horizontal" role="form" action="" method="post">
                        {% csrf_token %}
                        {% include 'html_pages/form_template.html' %}
                        <button type="submit" class="btn btn-success center-block">Submit</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}